### ISSUE TITLE
Write test script.

### ISSUE THREAD

**Issue by zokir** [Lumeos/server#22]
We need some way to automatically test api. 
This will be very helpful to someone who wants to know the whole workflow.

There is a way to do it even in postman.

**Comment by armmimic** [comment]
@fahdiq

**Comment by zokir** [comment]
@fahdiq wrote initial tests in postman. Then I wrote a framework to run those, and added more tests. Now we hold around 55 tests + some validation. So I will close this one. We should keep adding tests for every feature we write.
